// Platform and VRT category constants for BugGenie
// This file contains the full, alphabetized category lists for each platform

export const PLATFORMS = [
  {
    key: 'bugcrowd',
    label: 'Bugcrowd',
    categories: [
      'Account Takeover',
      'Authentication Bypass',
      'Business Logic Errors',
      'Cache Poisoning',
      'Clickjacking',
      'Command Injection',
      'Cross-Origin Resource Sharing (CORS) Misconfiguration',
      'Cross-Site Request Forgery (CSRF)',
      'Cross-Site Scripting (XSS)',
      'Cryptographic Issues',
      'Denial of Service',
      'Deserialization',
      'Directory Listing',
      'Directory Traversal',
      'File Inclusion',
      'HTTP Host Header Injection',
      'IDOR (Insecure Direct Object Reference)',
      'Improper Access Control',
      'Improper Input Validation',
      'Information Disclosure',
      'Insecure Deserialization',
      'Insecure Storage',
      'Insufficient Logging & Monitoring',
      'Insufficient Transport Layer Protection',
      'Local File Inclusion',
      'Open Redirect',
      'Privilege Escalation',
      'Remote Code Execution',
      'Server-Side Request Forgery (SSRF)',
      'Session Fixation',
      'Session Management',
      'SQL Injection',
      'Subdomain Takeover',
      'Unvalidated Redirects and Forwards',
      'XML External Entity (XXE) Injection',
    ].sort(),
  },
  {
    key: 'hackerone',
    label: 'HackerOne',
    categories: [
      'Array Index Underflow(CWE-129)',
      'Classic Buffer Overflow(CWE-120)',
      'Buffer Over-read(CWE-126)',
      'Buffer Underflow(CWE-124)',
      'Buffer Under-read(CWE-127)',
      'Cleartext Storage of Sensitive Information(CWE-312)',
      'Cleartext Transmission of Sensitive Information(CWE-319)',
      'CRLF Injection(CWE-93)',
      'Cross-site Scripting (XSS) - Reflected(CWE-79)',
      'Cross-site Scripting (XSS) - Stored(CWE-79)',
      'Deserialization of Untrusted Data(CWE-502)',
      'Double Free(CWE-415)',
      'Heap Overflow(CWE-122)',
      'Improper Access Control - Generic(CWE-284)',
      'Improper Certificate Validation(CWE-295)',
      'Improper Following of a Certificates Chain of Trust(CWE-296)',
      'Improper Null Termination(CWE-170)',
      'Inadequate Encryption Strength(CWE-326)',
      'Incorrect Calculation of Buffer Size(CWE-131)',
      'Insecure Direct Object Reference (IDOR)(CWE-639)',
      'Integer Overflow(CWE-190)',
      'Integer Underflow(CWE-191)',
      'Key Exchange without Entity Authentication(CWE-322)',
      'Man-in-the-Middle(CWE-300)',
      'Missing Required Cryptographic Step(CWE-325)',
      'NULL Pointer Dereference(CWE-476)',
      'Off-by-one Error(CWE-193)',
      'OS Command Injection(CWE-78)',
      'Out-of-bounds Read(CWE-125)',
      'Password in Configuration File(CWE-260)',
      'Path Traversal(CWE-22)',
      'Plaintext Storage of a Password(CWE-256)',
      'Privacy Violation(CWE-359)',
      'Remote File Inclusion(CWE-98)',
      'Resource Injection(CWE-99)',
      'Reusing a Nonce, Key Pair in Encryption(CWE-323)',
      'Reversible One-Way Hash(CWE-328)',
      'Security Through Obscurity(CWE-656)',
      'Session Fixation(CWE-384)',
      'Stack Overflow(CWE-121)',
      'Storing Passwords in a Recoverable Format(CWE-257)',
      'Type Confusion(CWE-843)',
      'Use After Free(CWE-416)',
      'Use of a Broken or Risky Cryptographic Algorithm(CWE-327)',
      'Use of a Key Past its Expiration Date(CWE-324)',
      'Use of Cryptographically Weak Pseudo-Random Number Generator (PRNG)(CWE-338)',
      'Use of Hard-coded Credentials(CWE-798)',
      'Use of Hard-coded Cryptographic Key(CWE-321)',
      'Use of Hard-coded Password(CWE-259)',
      'Use of Inherently Dangerous Function(CWE-242)',
      'Use of Insufficiently Random Values(CWE-330)',
      'Weak Cryptography for Passwords(CWE-261)',
      'Wrap-around Error(CWE-128)',
      'Write-what-where Condition(CWE-123)',
      'Use of Externally-Controlled Format String(CWE-134)',
      'Information Exposure Through an Error Message(CWE-209)',
      'Information Exposure Through Debug Information(CWE-215)',
      'Missing Encryption of Sensitive Data(CWE-311)',
      'Forced Browsing(CWE-425)',
      'HTTP Request Smuggling(CWE-444)',
      'Insufficiently Protected Credentials(CWE-522)',
      'Unprotected Transport of Credentials(CWE-523)',
      'Information Exposure Through Directory Listing(CWE-548)',
      'Insufficient Session Expiration(CWE-613)',
      'Unverified Password Change(CWE-620)',
      'Weak Password Recovery Mechanism for Forgotten Password(CWE-640)',
      'Improper Neutralization of HTTP Headers for Scripting Syntax(CWE-644)',
      'XML Entity Expansion(CWE-776)',
      'Reliance on Cookies without Validation and Integrity Checking in a Security Decision(CWE-784)',
      'LDAP Injection(CWE-90)',
      'XML Injection(CWE-91)',
      'Cross-site Scripting (XSS) - DOM(CWE-79)',
      'Improper Authentication - Generic(CWE-287)',
      'Command Injection - Generic(CWE-77)',
      'Cross-Site Request Forgery (CSRF)(CWE-352)',
      'Cross-site Scripting (XSS) - Generic(CWE-79)',
      'Cryptographic Issues - Generic(CWE-310)',
      'Uncontrolled Resource Consumption(CWE-400)',
      'HTTP Response Splitting(CWE-113)',
      'Information Disclosure(CWE-200)',
      'Memory Corruption - Generic(CWE-119)',
      'Violation of Secure Design Principles(CWE-657)',
      'Privilege Escalation(CAPEC-233)',
      'Code Injection(CWE-94)',
      'Server-Side Request Forgery (SSRF)(CWE-918)',
      'SQL Injection(CWE-89)',
      'UI Redressing (Clickjacking)(CAPEC-103)',
      'Open Redirect(CWE-601)',
      'XML External Entities (XXE)(CWE-611)',
      'Improper Restriction of Authentication Attempts(CWE-307)',
      'Business Logic Errors(CWE-840)',
      'Malware(CAPEC-549)',
      'Phishing(CAPEC-98)',
      'Insecure Storage of Sensitive Information(CWE-922)',
      'Client-Side Enforcement of Server-Side Security(CWE-602)',
      'Leftover Debug Code (Backdoor)(CWE-489)',
      'LLM01: Prompt Injection',
      'LLM02: Insecure Output Handling',
      'LLM03: Training Data Poisoning',
      'LLM04: Model Denial of Service',
      'LLM05: Supply Chain Vulnerabilities',
      'LLM06: Sensitive Information Disclosure',
      'LLM07: Insecure Plugin Design',
      'LLM08: Excessive Agency',
      'LLM09: Overreliance',
      'LLM10: Model Theft'
    ].sort(),
  },
  {
    key: 'google',
    label: 'Google',
    categories: [
      'Cross-site scripting (XSS)',
      'Cross-site request forgery (CSRF)',
      'Sensitive data exposure',
      'Remote Code Execution (RCE)',
      'Permissions Bypass',
      'Lockscreen Bypass',
      'Site Isolation Bypass',
      'Privilege Escalation',
      'Security UI Spoofing',
      'Exploit Mitigation Bypass',
      'Sandbox Escape',
      'Memory Corruption (in a non-sandboxed process)',
      'Memory Corruption (in a sandboxed process)',
      'Android issue',
      'Caching',
      'SSL vulnerability',
      'File Inclusion',
      'XML eXternal Entity (XXE)',
      'Information Leak',
      'Crypto Weakness',
      'Auth Bypass',
      'Mixed content',
      'Denial of Service (DoS)',
      'Memory Corruption',
      'Open Redirect',
      'SQL Injection (SQLi)',
      'Cross Site Script Inclusion (XSSI)',
      'Clickjacking',
      'Other'
    ].sort(),
  },
]; 