// Platform and VRT category constants for BugGenie
// This file contains the full, alphabetized category lists for each platform

export const PLATFORMS = [
  {
    key: 'bugcrowd',
    label: 'Bugcrowd',
    categories: [
      'Account Takeover',
      'Authentication Bypass',
      'Business Logic Errors',
      'Cache Poisoning',
      'Clickjacking',
      'Command Injection',
      'Cross-Origin Resource Sharing (CORS) Misconfiguration',
      'Cross-Site Request Forgery (CSRF)',
      'Cross-Site Scripting (XSS)',
      'Cryptographic Issues',
      'Denial of Service',
      'Deserialization',
      'Directory Listing',
      'Directory Traversal',
      'File Inclusion',
      'HTTP Host Header Injection',
      'IDOR (Insecure Direct Object Reference)',
      'Improper Access Control',
      'Improper Input Validation',
      'Information Disclosure',
      'Insecure Deserialization',
      'Insecure Storage',
      'Insufficient Logging & Monitoring',
      'Insufficient Transport Layer Protection',
      'Local File Inclusion',
      'Open Redirect',
      'Privilege Escalation',
      'Remote Code Execution',
      'Server-Side Request Forgery (SSRF)',
      'Session Fixation',
      'Session Management',
      'SQL Injection',
      'Subdomain Takeover',
      'Unvalidated Redirects and Forwards',
      'XML External Entity (XXE) Injection',
    ].sort(),
  },
  {
    key: 'hackerone',
    label: 'HackerOne',
    categories: [
      'Access Control Issues',
      'Authentication Issues',
      'Business Logic Errors',
      'Clickjacking',
      'Command Injection',
      'Cross-Origin Resource Sharing (CORS) Issues',
      'Cross-Site Request Forgery (CSRF)',
      'Cross-Site Scripting (XSS)',
      'Cryptographic Issues',
      'Denial of Service',
      'Directory Traversal',
      'File Upload Vulnerabilities',
      'IDOR (Insecure Direct Object Reference)',
      'Improper Input Validation',
      'Information Disclosure',
      'Insecure Deserialization',
      'Insecure Storage',
      'Insufficient Logging & Monitoring',
      'Insufficient Transport Layer Protection',
      'Local File Inclusion',
      'Open Redirect',
      'Privilege Escalation',
      'Remote Code Execution',
      'Server-Side Request Forgery (SSRF)',
      'Session Management',
      'SQL Injection',
      'Subdomain Takeover',
      'Unvalidated Redirects and Forwards',
      'XML External Entity (XXE) Injection',
    ].sort(),
  },
  {
    key: 'google',
    label: 'Google',
    categories: [
      'Account Hijacking',
      'Authentication Bypass',
      'Business Logic Errors',
      'Clickjacking',
      'Command Injection',
      'Cross-Origin Resource Sharing (CORS) Issues',
      'Cross-Site Request Forgery (CSRF)',
      'Cross-Site Scripting (XSS)',
      'Cryptographic Issues',
      'Denial of Service',
      'Directory Traversal',
      'File Inclusion',
      'IDOR (Insecure Direct Object Reference)',
      'Improper Access Control',
      'Improper Input Validation',
      'Information Disclosure',
      'Insecure Deserialization',
      'Insecure Storage',
      'Insufficient Logging & Monitoring',
      'Insufficient Transport Layer Protection',
      'Local File Inclusion',
      'Open Redirect',
      'Privilege Escalation',
      'Remote Code Execution',
      'Server-Side Request Forgery (SSRF)',
      'Session Management',
      'SQL Injection',
      'Subdomain Takeover',
      'Unvalidated Redirects and Forwards',
      'XML External Entity (XXE) Injection',
    ].sort(),
  },
]; 